mouse_sensitivity: 20
scroll_sensitivity: 2
dead_zone: .0001
mapping:
  # Controller event: Mouse or keyboard event
  BUTTON_A: MOUSE_LEFT
  BUTTON_B: MOUSE_BACK
  BUTTON_X: MOUSE_RIGHT
  BUTTON_Y: MOUSE_MIDDLE
  ANALOG_RIGHT_Y: MOUSE_SCROLL
  ANALOG_LEFT_X: MOUSE_X
  ANALOG_LEFT_Y: MOUSE_Y
  BUTTON_START: KEYBOARD_TOGGLE_ON_SCREEN_KEYBOARD
  TRIGGER_RIGHT: KEYBOARD_COMMAND_ENTER
  TRIGGER_LEFT: KEYBOARD_COMMAND_ESC
  BUTTON_RB: KEYBOARD_COMMAND_BACKSPACE
  DPAD_UP: KEYBOARD_COMMAND_UP
  DPAD_RIGHT: KEYBOARD_COMMAND_RIGHT
  DPAD_DOWN: KEYBOARD_COMMAND_DOWN
  DPAD_LEFT: KEYBOARD_COMMAND_LEFT


## Controller events:
# DPAD_UP
# DPAD_RIGHT
# DPAD_DOWN
# DPAD_LEFT
# BUTTON_A
# BUTTON_B
# BUTTON_X
# BUTTON_Y
# BUTTON_LB
# BUTTON_RB
# BUTTON_SELECT
# BUTTON_START
# BUTTON_HOME
# BUTTON_LS
# BUTTON_RS 
# ANALOG_LEFT_X
# ANALOG_LEFT_Y
# ANALOG_RIGHT_X
# ANALOG_RIGHT_Y
# TRIGGER_LEFT
# TRIGGER_RIGHT


## Mouse events:
# MOUSE_LEFT
# MOUSE_RIGHT
# MOUSE_SCROLL
# MOUSE_MIDDLE
# MOUSE_BACK
# MOUSE_FORWARD
# MOUSE_X
# MOUSE_Y


## Keyboard events:
# KEYBOARD_TOGGLE_ON_SCREEN_KEYBOARD
# KEYBOARD_COMMAND_SHIFT
# KEYBOARD_COMMAND_CONTROL
# KEYBOARD_COMMAND_ALT
# KEYBOARD_COMMAND_CAPS
# KEYBOARD_COMMAND_TAB
# KEYBOARD_COMMAND_DEL
# KEYBOARD_COMMAND_SUPER
# KEYBOARD_COMMAND_ENTER
# KEYBOARD_COMMAND_BACKSPACE
# KEYBOARD_COMMAND_UP
# KEYBOARD_COMMAND_DOWN
# KEYBOARD_COMMAND_LEFT
# KEYBOARD_COMMAND_RIGHT
# KEYBOARD_COMMAND_ESCAPE
# KEYBOARD_SPACE
# KEYBOARD_LOWERCASE_A
# KEYBOARD_LOWERCASE_B
# KEYBOARD_LOWERCASE_C
# KEYBOARD_LOWERCASE_D
# KEYBOARD_LOWERCASE_E
# KEYBOARD_LOWERCASE_F
# KEYBOARD_LOWERCASE_G
# KEYBOARD_LOWERCASE_H
# KEYBOARD_LOWERCASE_I
# KEYBOARD_LOWERCASE_J
# KEYBOARD_LOWERCASE_K
# KEYBOARD_LOWERCASE_L
# KEYBOARD_LOWERCASE_M
# KEYBOARD_LOWERCASE_N
# KEYBOARD_LOWERCASE_O
# KEYBOARD_LOWERCASE_P
# KEYBOARD_LOWERCASE_Q
# KEYBOARD_LOWERCASE_R
# KEYBOARD_LOWERCASE_S
# KEYBOARD_LOWERCASE_T
# KEYBOARD_LOWERCASE_U
# KEYBOARD_LOWERCASE_V
# KEYBOARD_LOWERCASE_W
# KEYBOARD_LOWERCASE_X
# KEYBOARD_LOWERCASE_Y
# KEYBOARD_LOWERCASE_Z
# KEYBOARD_UPPERCASE_A
# KEYBOARD_UPPERCASE_B
# KEYBOARD_UPPERCASE_C
# KEYBOARD_UPPERCASE_D
# KEYBOARD_UPPERCASE_E
# KEYBOARD_UPPERCASE_F
# KEYBOARD_UPPERCASE_G
# KEYBOARD_UPPERCASE_H
# KEYBOARD_UPPERCASE_I
# KEYBOARD_UPPERCASE_J
# KEYBOARD_UPPERCASE_K
# KEYBOARD_UPPERCASE_L
# KEYBOARD_UPPERCASE_M
# KEYBOARD_UPPERCASE_N
# KEYBOARD_UPPERCASE_O
# KEYBOARD_UPPERCASE_P
# KEYBOARD_UPPERCASE_Q
# KEYBOARD_UPPERCASE_R
# KEYBOARD_UPPERCASE_S
# KEYBOARD_UPPERCASE_T
# KEYBOARD_UPPERCASE_U
# KEYBOARD_UPPERCASE_V
# KEYBOARD_UPPERCASE_W
# KEYBOARD_UPPERCASE_X
# KEYBOARD_UPPERCASE_Y
# KEYBOARD_UPPERCASE_Z
# KEYBOARD_NUM_0
# KEYBOARD_NUM_1
# KEYBOARD_NUM_2
# KEYBOARD_NUM_3
# KEYBOARD_NUM_4
# KEYBOARD_NUM_5
# KEYBOARD_NUM_6
# KEYBOARD_NUM_7
# KEYBOARD_NUM_8
# KEYBOARD_NUM_9